apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modify-pods
rules:
  - apiGroups: ["","coordination.k8s.io"]
    resources: 
    - leases
    - nodes
    verbs:
      - get
      - watch
      - list
